version: 2.1
jobs:
  build:
    machine: true
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Build image and copy artifact
          command: make copy
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - rootfs.ext2
  github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Upload artifact to release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} /tmp/workspace/rootfs.ext2
  store_artifact:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/rootfs.ext2
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Docker Hub
      - github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - store_artifact:
          requires:
            - build
