name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make -j$(nproc)

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: rootfs.ext2
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Publish to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag cartesi/image-rootfs:devel cartesi/image-rootfs:${GITHUB_REF:11}
          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
          docker push cartesi/image-rootfs:${GITHUB_REF:11}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
